### ISSUE TITLE
(bug) visual bugs in main screen

### ISSUE THREAD

**Issue by WeeskyBDW** [relagit/relagit#12]
### What happened?

:wave:
I just installed relagit (found it from a dev news video) and when i start it i have two graphical bugs in the main screens:

In windowed mode, a bug make main screen look like they is text over text (see screenshot below)
![image](https://github.com/relagit/relagit/assets/36575072/afd27e65-9245-4bf0-bc10-30514286b7bb)

in full screen, black screen with only button and version visible 
![image](https://github.com/relagit/relagit/assets/36575072/e0f8d5bb-73b5-440e-a057-131b215f4213)

I'm using Linux Mint 21.3 Victoria
Kernel version: Linux version 5.15.0-92-generic
Installed with the deb archive

if you need any other information (i searched what can i provide but i dont know what can change electron behaviors), feel free to ask 

### Version

0.12.9

### What systems are you seeing the problem on?

Linux

### Relevant log output

```shell
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
Checking for update
[RelaGit] Startup (production)
[RelaGit] Version: 0.12.9
[RelaGit] Running on: linux x64
```

### Confirmations

- [X] I have searched open and closed issues for duplicates
- [X] I have read the relevant documentation
- [X] I have read the CONTRIBUTING document
- [X] I have read the CODE_OF_CONDUCT document

**Comment by TheCommieAxolotl** [comment]
Thank you for the bug report, I have some suspicions on what's causing some of those issues and I'll have a look tomorrow.

**Comment by WeeskyBDW** [comment]
Thanks for the rapid response. I just saw another problem idk if it need it's specific issue (if so, i'll): When launching  the app, it show as a small rectangle without logo wich is difficult to click well on it

**Comment by WeeskyBDW** [comment]
Oh and i alqo found that when we highlight text in onboarding screen we can undo that (text will stay highlight)

**Comment by TheCommieAxolotl** [comment]
> Thanks for the fast response. I just saw another problem idk if it need it's specific issue (if so, i'll): When launching the app, it show as a small rectangle without logo wich is difficult to click well on it

Can you send a screenshot or recording of this? I don't really know what you mean

**Comment by WeeskyBDW** [comment]
> > Thanks for the fast response. I just saw another problem idk if it need it's specific issue (if so, i'll): When launching the app, it show as a small rectangle without logo wich is difficult to click well on it
> 
> Can you send a screenshot or recording of this? I don't really know what you mean

https://github.com/relagit/relagit/assets/36575072/e1f6468a-3ef5-424d-9672-e16214385223.

**Comment by TheCommieAxolotl** [comment]
Sorry, I'm afraid it is:
<img width="471" alt="Screenshot 2024-02-13 at 9 33 23 pm" src="https://github.com/relagit/relagit/assets/87679354/0d071edc-5a27-4d1e-a746-ac56782bfdbe">

**Comment by WeeskyBDW** [comment]
https://github.com/relagit/relagit/assets/36575072/44496cd5-ba75-4981-a445-d2fce5ef08f4

mb

**Comment by WeeskyBDW** [comment]
Even if i record again i have that issue; I even tried to check file validity and no errors (Github/our navigators are brokens ?)

**Comment by WeeskyBDW** [comment]
ok i upload it on [Youtube](<https://youtu.be/CyBTpnUNRQM>) (unlisted)

**Comment by TheCommieAxolotl** [comment]
Ah, I get what you mean, I can look into fixing that as well.

[b5c1822](https://github.com/relagit/relagit/commit/b5c18229992e55b85a052c4bb81f84a0d83c9515) should have fixed the doubling problem, so you can try v0.12.10 when the CI finishes.

**Comment by WeeskyBDW** [comment]
Bugs are fixed thx. One question thought : is normal that app icon seem not set ? (On Linux mint i have the default gear icon) ?

**Comment by TheCommieAxolotl** [comment]
I have to look into that one, the app might just be loading the wrong file
