### ISSUE TITLE
(bug) One or more of your configuration files are corrupt. Please reset them.

### ISSUE THREAD

**Issue by gabrielstuff** [relagit/relagit#19]
### What happened?

After installing the app on a mac book pro M1 pro max and opened it, I got an error.

I followed the tour and added one repo.

See the image : 
<img width="1054" alt="image" src="https://github.com/relagit/relagit/assets/285033/6f87436f-c86a-4ebc-b7da-517ac8b90835">

I can close the window error, but it pops up every time.

The UI is really nice, well done !

### Version

0.14.8 (c4eb20c)

### What systems are you seeing the problem on?

MacOS (OSX)

### Relevant log output

```shell
Unexpected non-whitespace character after JSON at
position 260 (line 16 column 2)
SyntaxError: Unexpected non-whitespace character
after JSON at position 260 (line 16 column 2)
at JSON. parse (<anonymous>)
at d1. load
(file:///Applications/RelaGit.app/Contents/Reso...
VuhXhxAJ. js: 14:3054)
at
file:///Applications/RelaGit.app/Contents/Resou...
VuhXhxAJ.js: 14:2421
```

### Confirmations

- [X] I have searched open and closed issues for duplicates
- [X] I have read the relevant documentation
- [X] I have read the CONTRIBUTING document
- [X] I have read the CODE_OF_CONDUCT document

**Comment by TheCommieAxolotl** [comment]
Thanks for the issue, I'm in progress on working on fixing this in #18 (same error) so you can track progress there.
