### ISSUE TITLE
(bug)  Clone using SSH

### ISSUE THREAD

**Issue by rishikesh2003** [relagit/relagit#21]
### What happened?

I tried cloning a private repository using the client, it clones from the normal url instead of using the SSH one. So I am getting the error `fatal : could not read username for https://github.com`

![image](https://github.com/relagit/relagit/assets/58881733/190aeef5-14c3-461a-8ba5-772c6ffe0cf4)

### Version

0.14.10

### What systems are you seeing the problem on?

Linux

### Confirmations

- [X] I have searched open and closed issues for duplicates
- [X] I have read the relevant documentation
- [X] I have read the CONTRIBUTING document
- [X] I have read the CODE_OF_CONDUCT document

**Comment by TheCommieAxolotl** [comment]
Thanks for the issue, I'll be sure to check this out asap!

**Comment by TheCommieAxolotl** [comment]
Added in [c122d85](https://github.com/relagit/relagit/commit/c122d85). (Requires previous ssh setup)
