### ISSUE TITLE
Macos issue

### ISSUE THREAD

**Issue by unacorbatanegra** [relagit/relagit#22]
<img width="283" alt="image" src="https://github.com/relagit/relagit/assets/44511181/2e332cd8-2643-4ec3-81c7-e3c6313fa0a0">
<img width="274" alt="image" src="https://github.com/relagit/relagit/assets/44511181/20dcc23f-b0fe-4ef0-bc18-8b42e503ab46">

**Comment by TheCommieAxolotl** [comment]
Thank you for the issue!

This is unfortunately not something I can remove at the moment, It relates to how macOS deals with ad-hoc signed apps.
**The solution is to open the app in Finder and *Right-Click then press "Open"*, then you will be presented with a similar modal to the one in your image, but with an "OK" button which allows you to open the app**

Feel free to reply if you would like some more help!

**Comment by unacorbatanegra** [comment]
Worked for me, thanks

**Comment by ZaLiTHkA** [comment]
it would seem Apple have changed things and the following statement is no longer totally correct:

> **The solution is to open the app in Finder and _Right-Click then press "Open"_, then you will be presented with a similar modal to the one in your image, but with an "OK" button which allows you to open the app**

on the current latest macOS 15.2 release, the only options I saw when selecting "Open" from the context menu in Finder were "Done" and "Move to Trash", as per the following screenshot:

![Image](https://github.com/user-attachments/assets/d896cd67-2d88-47fe-b828-52629aff9b8d)

---

if you find yourself in the same situation:

1. open System Settings and select "Privacy & Security"

![Image](https://github.com/user-attachments/assets/17a5cf86-0c59-41cb-a0a7-dffdd9a6e0b6)

2. click "Open Anyway" to show another dialog window

![Image](https://github.com/user-attachments/assets/adba17be-51af-4b95-b75d-9a2dc2153b76)

3. click the "Open Anyway" button to launch the app

after doing this once, RelaGit should launch without issue from Launcher and Dock icons, at least until the next time you update... in which case, this scenario may come up again.

**Comment by neeraj-ec** [comment]
You can use command:

```bash
xattr -rd com.apple.quarantine /Applications/RelaGit.app
```
