### ISSUE TITLE
Dark theme Issue on Ubuntu 22.04

### ISSUE THREAD

**Issue by rodrigoGA** [relagit/relagit#24]
### What happened?

Dark theme doesn't work on Ubuntu 22.04
![Captura desde 2024-05-07 23-28-55](https://github.com/relagit/relagit/assets/2334523/3b4f68a8-a9c3-4f83-9cc9-1f565e2a5ab6)

### Version

0.14.12

### Confirmations

- [ ] I have searched open and closed issues for duplicates
- [ ] I have read the relevant documentation
- [ ] I have read the CONTRIBUTING document
- [ ] I have read the CODE_OF_CONDUCT document

**Comment by TheCommieAxolotl** [comment]
Thanks for the issue! Can you please send the result of running the following in a terminal:
```bash
node --eval="console.log(require('process').platform)"
```

**Comment by beruic** [comment]
I can confirm the issue on Ubuntu 20.04

@TheCommieAxolotl here is what I get:
```
$ node --eval="console.log(require('process').platform)"
linux
```
