### ISSUE TITLE
Use proper user data location across platforms

### ISSUE THREAD

**Issue by kra-mo** [relagit/relagit#30]
For macOS, `~/.relagit` is the correct location, but Linux follows the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and Windows application data is placed in [`%LOCALAPPDATA%`](https://learn.microsoft.com/en-us/windows/win32/shell/knownfolderid).

In human-readable terms, if the platform is `win32`, use the `LOCALAPPDATA` environment variable followed by `relagit` without the dot prefix. For `linux`, use `$XDG_DATA_HOME/relagit` with a fallback to `~/.local/share/relagit` as setting the environment variable is not required as per the spec and thus a lot of distros which use the default `~/.local/share/` do not have it set.

PS: [Linux users can be very annoying if you don't follow the spec](https://wiki.archlinux.org/title/XDG_Base_Directory#Support) x)

**Comment by TheCommieAxolotl** [comment]
Would massively appreciate if you could verify that commit implements the changes correctly as I currently don't have a linux/windows machine to run the dev build on.

**Comment by kra-mo** [comment]
The Linux part seems to work, I can't verify with Windows specifically but as the code seems the same, only the directory names differ, I would guess that part works too ^^

**Comment by kra-mo** [comment]
The environment variable for Linux should be `XDG_DATA_HOME`, not `XDG_CONFIG_HOME`, they are two different variables and RelaGit already uses `XDG_CONFIG_HOME` through Electron for different data:

![Screenshot from 2024-05-18 13-41-38](https://github.com/relagit/relagit/assets/93832451/f8f0225a-eb9c-4ec8-ad56-7d26e0084a79)


Other than that, the Linux part seems to work, I can't verify with Windows specifically but as the code seems the same, only the directory names differ, I would guess that part works too ^^

**Comment by TheCommieAxolotl** [comment]
Ah, thanks
