### ISSUE TITLE
Icon not displaying correctly in Ubuntu

### ISSUE THREAD

**Issue by iglnierod** [relagit/relagit#31]
### What happened?

Hi! I know someone told you about this some time ago but as it is not fixed yet I wanted to remind you. 
The app icon is not displaying as it's supposed to in Ubuntu.
![image](https://github.com/relagit/relagit/assets/115586378/6eb7ef46-0151-40f2-911f-1a0bc1aa5867)

### Version

0.15.0

### What systems are you seeing the problem on?

Linux

### Confirmations

- [X] I have searched open and closed issues for duplicates
- [X] I have read the relevant documentation
- [X] I have read the CONTRIBUTING document
- [X] I have read the CODE_OF_CONDUCT document

**Comment by TheCommieAxolotl** [comment]
Thanks for the issue, do you mind sharing which archive you downloaded/what the file type was?

**Comment by iglnierod** [comment]
> Thanks for the issue, do you mind sharing which archive you downloaded/what the file type was?

I downloaded the .deb file

**Comment by kra-mo** [comment]
There are two issues at play here, at least judging from the `.rpm` package:

1. RelaGit installs its icon in `/usr/share/icons/hicolor/0x0`, which is a nonsensical directory. `0x0` should be replaced with the actual resolution of the icon.
2. 1024x1024, which is the icon size currently shipped by RelaGit is too big. GNOME Only looks for icons up to 512x512, which is what the icon should be downscaled to and then placed in `/usr/share/icons/hicolor/512x512`.

**Comment by jvereecken** [comment]
Just wanted to share that this issue is still present in 0.16.5
