### ISSUE TITLE
(bug) "relagit" has not been opened

### ISSUE THREAD

**Issue by Hernanarica** [relagit/relagit#51]
### What happened?

When I download the RelaGit-mac-arm64.zip version for Mac M2 I get that alert and it doesn't let me start the application

<img width="355" alt="Captura de pantalla 2024-12-23 a las 8 26 08 a  m" src="https://github.com/user-attachments/assets/d3aeaab8-b0dc-451e-88d1-403ef65d9018" />

### Version

0.16.8

### What systems are you seeing the problem on?

MacOS (OSX)

### Relevant log output

```shell
Apple has not been able to verify that RelaGit.app does not contain malware that could harm your Mac or compromise your privacy.
```

### Confirmations

- [ ] I have searched open and closed issues for duplicates
- [ ] I have read the relevant documentation
- [ ] I have read the CONTRIBUTING document
- [ ] I have read the CODE_OF_CONDUCT document

**Comment by TheCommieAxolotl** [comment]
Yes unfortunately Apple treats apps downloaded from the internet as "unsafe".

You should be able to dismiss this alert by:
1. Locating the app in Finder (`/Applications/RelaGit.app`)
2. Right-Clicking and pressing open
3. Pressing open anyway (or an equivalent button)

**Comment by Hernanarica** [comment]
@TheCommieAxolotl Hi! I already have it in /Applications, and yes, I right-clicked to open it and that alert appeared, I can't start it.

<img width="403" alt="Captura de pantalla 2024-12-23 a las 8 39 35 a  m" src="https://github.com/user-attachments/assets/92ca87df-48fd-4fe2-9544-fa8897e55a4b" />

**Comment by TheCommieAxolotl** [comment]
In that case, can you try running the following in Terminal and then re-opening?
```bash
xattr -d com.apple.quarantine /Applications/RelaGit.app
```

**Comment by Hernanarica** [comment]
@TheCommieAxolotl Thank you very much! Now it opens and works fine.

**Comment by TheCommieAxolotl** [comment]
Good to hear!

**Comment by daeho-ro** [comment]
Is this app could be signed by an apple developer account for someday? Just curious. :)
